language: clojure
notifications:
  email:
    on_success: never
    on_failure: change
services: postgresql
before_script:
  - psql -c 'create database webrtclojure;' -U postgres
  - lein migrate
jdk: oraclejdk8
